application:
  name: "familie-ef-sak"
server:
  servlet:
    context-path: /

spring:
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://A01DBVL010.adeo.no:5432/familie-ef-sak
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1


management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

ACCEPTED_CLIENTS: ${EF_SAK_FRONTEND_CLIENT_ID}, ${EF_MOTTAK_CLIENT_ID}
