server:
  port: 8093
  servlet:
    context-path: /

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${EF_SAK_FRONTEND_CLIENT_ID}
    proxyurl:
    cookie_name: azure_token
