spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ef-sak

AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token

VEILEDER_ROLLE: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"
SAKSBEHANDLER_ROLLE: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"
BESLUTTER_ROLLE: "01166863-22f1-4e16-9785-d7a05a22df74"